name: milow_workspace
description: A monorepo for the Milow project containing Driver and Admin apps.
publish_to: 'none'

environment:
  sdk: ^3.10.1

workspace:
  - apps/driver
  - apps/terminal
  - packages/core
