name: milow
description: "A Semi Trucking app for drivers and companies to manage trips, track fuel, and export reports"
publish_to: "none"
version: 0.0.1

# Repository information
# homepage: https://github.com/maninder-mike/milow
# repository: https://github.com/maninder-mike/milow

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  google_fonts: ^6.3.2
  go_router: ^17.0.0
  flutter_dotenv: ^6.0.0
  local_auth: ^3.0.0
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.2.1
  crypto: ^3.0.3
  http: ^1.2.2
  pdf: ^3.11.1
  path_provider: ^2.1.5
  open_file: ^3.5.9
  share_plus: ^12.0.1
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/milow_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/milow_icon.png"

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
