name: milow_workspace
description: A monorepo for the Milow project containing Driver and Admin apps.
publish_to: 'none'

environment:
  sdk: ^3.10.7

workspace:
  - apps/driver
  - apps/terminal
  - packages/core
dev_dependencies:
  very_good_analysis: ^10.0.0
