name: terminal
description: "Milow Terminal - Fleet management application for dispatchers and admins"
publish_to: "none"
version: 0.0.3+28

environment:
  sdk: ^3.10.7

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Core
  intl: any
  go_router: ^17.0.0
  http: ^1.1.0

  # State Management
  flutter_riverpod: ^3.1.0
  riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # UI - Fluent Design
  fluent_ui: ^4.13.0
  fluentui_system_icons: ^1.1.273
  google_fonts: ^7.1.0
  system_theme: ^3.1.2

  # Backend
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0

  # Security
  local_auth: ^3.0.0
  flutter_secure_storage: ^10.0.0

  # Desktop
  window_manager: ^0.5.1
  file_selector: ^1.1.0

  # Networking & Utils
  fpdart: ^1.1.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  app_links: ^6.4.1
  shared_preferences: ^2.3.5
  flutter_local_notifications: ^19.5.0

  # PDF & Printing
  pdf: ^3.11.0
  printing: ^5.13.1
  path_provider: ^2.1.2

  # Workspace Packages
  milow_core:
    path: ../../packages/core
  textfield_tags: ^3.0.1

  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  firebase_analytics: ^12.1.1
  firebase_remote_config: ^6.1.4
  firebase_performance: ^0.11.1+3
  firebase_messaging: ^16.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  uuid: ^4.5.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  supercluster: ^3.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.4
  mockito: ^5.6.1
  msix: ^3.16.8
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter_launcher_icons:
  image_path: "assets/images/terminal_icon.png"
  android: false
  ios: false
  macos:
    generate: true
  windows:
    generate: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/terminal_icon.png

msix_config:
  display_name: Milow Terminal
  publisher_display_name: Maninder Singh
  identity_name: ManinderSingh.milowterminal

  logo_path: assets/images/terminal_icon.png
  publisher: CN=503D7524-2660-491B-86EF-F923C5886DDE
  store: true
  capabilities: internetClient
  languages: en-us
  architecture: x64
  output_name: MilowTerminal
