name: milow
description: "A Semi Trucking app for drivers and companies to manage trips, track fuel, and export reports"
publish_to: "none"
version: 1.0.1+133

homepage: https://maninder.co.in/milow
repository: https://github.com/maninder-mike/milow

environment:
  sdk: ^3.10.7

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  intl: any
  provider: ^6.1.5+1
  go_router: ^17.0.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  dynamic_color: ^1.7.0
  cached_network_image: ^3.3.1

  # Backend
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  firebase_messaging: ^16.1.0
  firebase_analytics: ^12.1.1
  firebase_remote_config: ^6.1.4
  firebase_performance: ^0.11.1+3
  flutter_local_notifications: ^20.0.0

  # Security
  local_auth: ^3.0.0
  crypto: ^3.0.3
  app_device_integrity:
    git:
      url: https://github.com/Maninder-mike/app_device_integrity.git
      ref: master

  # Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  countries_world_map: ^1.3.0

  # Media & Files
  image_picker: ^1.2.1
  pdf: ^3.11.1
  open_file: ^3.5.9
  share_plus: ^12.0.1

  # Networking & Utils
  http: ^1.2.2
  url_launcher: ^6.3.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  connectivity_plus: ^7.0.0
  uuid: ^4.0.0

  # Auth
  google_sign_in: ^7.2.0

  # ML
  google_mlkit_text_recognition: ^0.15.0

  # Workspace Packages
  milow_core:
    path: ../../packages/core
  animations: ^2.1.1
  csv: ^6.0.0
  google_mlkit_document_scanner: ^0.4.0
  flutter_image_compress: ^2.4.0
  flutter_secure_storage: ^10.0.0
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  hive_ce_generator: ^1.6.0
  build_runner: ^2.4.8
  mockito: ^5.6.1
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  leak_tracker_flutter_testing: ^3.0.10

flutter_launcher_icons:
  android: true
  ios: false
  macos:
    generate: true
  image_path: "assets/images/milow_icon.png"
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/images/milow_icon_foreground.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env
