name: milow
description: "A Semi Trucking app for drivers and companies to manage trips, track fuel, and export reports"
publish_to: "none"
version: 0.0.6+25

homepage: https://maninder.co.in/milow
repository: https://github.com/maninder-mike/milow

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  intl: any
  provider: ^6.1.5+1
  go_router: ^17.0.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  dynamic_color: ^1.7.0
  cached_network_image: ^3.3.1

  # Backend
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0

  # Security
  local_auth: ^3.0.0
  crypto: ^3.0.3

  # Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  countries_world_map: ^1.3.0

  # Media & Files
  image_picker: ^1.2.1
  pdf: ^3.11.1
  open_file: ^3.5.9
  share_plus: ^12.0.1

  # Networking & Utils
  http: ^1.2.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.1.2
  path: ^1.9.1
  connectivity_plus: ^7.0.0
  uuid: ^4.0.0

  # Auth
  google_sign_in: ^7.2.0

  # ML
  google_mlkit_text_recognition: ^0.15.0

  # Workspace Packages
  milow_core:
    path: ../../packages/core
  animations: ^2.1.1
  csv: ^6.0.0
  google_mlkit_document_scanner: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  hive_ce_generator: ^1.6.0
  build_runner: ^2.4.8
  mockito: ^5.6.1
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/mipmap-xxxhdpi/milow_driver_icon.png"
  adaptive_icon_background: "#007AFF"
  adaptive_icon_foreground: "assets/images/milow_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env
